Plutip core
mlabs-haskell/plutip pull request #169
Opened 2023-01-15 23:37 UTC by zmrocze

WIP

2023-01-19 22:52 UTC, zmrocze commented
Specifically changes to `plutip-server`:
 - fix reporting `NegativeLovelace` (previously this failed too early in json parsing)
 - remove handling of `PlutipServerError` as it was never thrown
 - TODO ex units
 
Good improvement would be to report in `ClusterStartupFailureReason` a case when wallet funding fails due to requested utxo distribution not satisfying the minimum Ada requirement. When this happens the cluster raises [this exception](https://github.com/mlabs-haskell/plutip/blob/b683b3d10f3903158b71044a3330038f0874fcc7/src/Plutip/Launch/Cluster.hs#L430).

2023-01-23 10:09 UTC, klntsky requested changes
Thanks Karol! We will handle these comments by ourselves.

2023-01-23 10:09 UTC, klntsky commented on src/Plutip/Launch/Cluster.hs
> +    --      traceCounters tr cs
What value does this commented-out code provide?

2023-01-23 10:09 UTC, klntsky commented on src/Plutip/DistributeFunds.hs
> +    nullTracer -- todo: fix tracer to be not `nullTracer`
Why this TODO? What's a better option than nullTracer?

2023-01-23 10:09 UTC, klntsky commented on src/Plutip/Cluster.hs
> +isPrefixOf :: (Eq a) => [a] -> [a] -> Bool
It exists in `Data.List`

2023-01-23 10:09 UTC, klntsky commented on src/Plutip/Cluster.hs
> +    >>= dieOnError
We should not terminate, we need to throw.

2023-02-17 10:12 UTC, merged