Update and improve docs pt.1, plus misc fixes
mlabs-haskell/plutip pull request #177
Opened 2023-04-28 11:59 UTC by aske

2023-04-30 09:45 UTC, klntsky commented on README.md
> +You can use it to start up disposable private network with arbitrary amount of funded addresses (providing keys for those addresses as well).
Plutip generates these keys, not the user

2023-04-30 09:47 UTC, klntsky commented on README.md
> +One of its features is the ability to test contracts on disposable private networks which Plutip sets up, see [plutip-testing](https://github.com/Plutonomicon/cardano-transaction-lib/blob/develop/doc
Please mention that users should not install plutip if the want to use it with ctl, because it provides everything needed

2023-05-01 20:07 UTC, zmrocze commented
other than the two comments all the changes look correct

2023-05-02 12:14 UTC, zmrocze approved these changes

2023-05-02 12:23 UTC, aske commented on README.md
> +You can use it to start up disposable private network with an arbitrary amount of funded addresses (Plutip will provide corresponding PKHs and key pairs as well).
Hm, feels like it doesn't give enough info this way

2023-05-29 15:30 UTC, klntsky requested changes

2023-05-29 15:30 UTC, klntsky commented on README.md
> +You can use it to start up disposable private network with an arbitrary amount of funded addresses (Plutip will provide corresponding PKHs and key pairs as well).
```suggestion
You can use it to start up disposable private network with an arbitrary amount of funded addresses (Plutip will provide corresponding key pairs as well).
```

PKH is a part of the key pair

2023-05-29 15:30 UTC, klntsky commented on README.md
> +**TL;DR**: plutip gets you a cardano node socket where the node belongs to a small cluster on a private network, optionally you can prefund addresses with ADA.
```suggestion
**TL;DR**: plutip gets you a cardano node socket where the node belongs to a small cluster on a private network, and you can prefund addresses with ADA.
```

2023-06-02 07:59 UTC, klntsky commented
All good

2023-06-02 11:47 UTC, merged